"""
CLI entry point.

Usage (Colab one-liner generated by StreamLift UI):
    streamlift-worker \\
        --worker-id    "uuid" \\
        --auth-token   "token" \\
        --api-url      "https://your-app.com"

Compute type, download location and the Pinggy token are fetched from the
backend at startup via /api/worker/config. The corresponding flags remain
optional for backwards compatibility and act as a fallback when the config
endpoint is unreachable. Legacy Mega credentials (--mega-email/--mega-password)
are only embedded for legacy workers that still store them.
"""

import argparse
import sys

from streamlift_worker import api
from streamlift_worker.config import COMPUTE_CONFIG, WorkerConfig

COMPUTE_TYPES = tuple(COMPUTE_CONFIG.keys())          # ("low", "medium", "high")
DOWNLOAD_LOCATIONS = ("local", "mega")


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="streamlift-worker",
        description="StreamLift distributed download worker",
    )

    p.add_argument("--worker-id",      required=True,  help="Worker UUID from StreamLift dashboard")
    p.add_argument("--auth-token",     required=True,  help="Permanent auth token for this worker")
    p.add_argument("--api-url",        required=True,  help="StreamLift backend base URL")
    p.add_argument("--compute-type",   choices=list(COMPUTE_TYPES), help="Fallback compute type (fetched from backend by default)")
    p.add_argument("--location",       choices=list(DOWNLOAD_LOCATIONS),
                   dest="download_location", help="Fallback download location (fetched from backend by default)")
    p.add_argument("--pinggy-token",   help="Fallback Pinggy tunnel token (fetched from backend by default)")
    p.add_argument("--mega-email",     default="",     help="Legacy: required for mega location when using credentials")
    p.add_argument("--mega-password",  default="",     help="Legacy: required for mega location when using credentials")
    p.add_argument("--port",           default=8000,   type=int, help="Local server port (default 8000)")
    p.add_argument("--version",        action="version", version=f"%(prog)s {_get_version()}")

    return p.parse_args()


def _bootstrap_config(args: argparse.Namespace) -> WorkerConfig:
    """Resolve the full worker config: /api/worker/config first, CLI flags as fallback."""
    api_base_url = args.api_url.rstrip("/")

    # Config endpoint is authoritative; CLI flags are the fallback if it's unavailable.
    remote = api.fetch_worker_config(args.worker_id, args.auth_token, api_base_url)

    compute_type = args.compute_type
    if compute_type is None and remote:
        compute_type = remote.get("computeType")
    if compute_type not in COMPUTE_TYPES:
        print("Could not determine compute type (via /api/worker/config or --compute-type).")
        sys.exit(1)

    download_location = args.download_location
    if download_location is None and remote:
        download_location = remote.get("downloadLocation")
    if download_location not in DOWNLOAD_LOCATIONS:
        print("Could not determine download location (via /api/worker/config or --location).")
        sys.exit(1)

    pinggy_token = args.pinggy_token
    if not pinggy_token and remote:
        pinggy_token = remote.get("pinggyToken") or ""

    # Session-only workers omit --mega-email/--mega-password and fetch their
    # Mega session from the backend at startup.
    if download_location == "mega" and not (args.mega_email and args.mega_password):
        print("Mega credentials not provided — will load Mega session from backend at startup.")
        if not args.mega_email and not args.mega_password:
            print("Using session-only mode (no passwords on the command line).")

    return WorkerConfig(
        worker_id=         args.worker_id,
        auth_token=        args.auth_token,
        api_base_url=      api_base_url,
        compute_type=      compute_type,
        download_location= download_location,
        pinggy_token=      pinggy_token,
        mega_email=        args.mega_email,
        mega_password=     args.mega_password,
        server_port=       args.port,
    )


def _get_version() -> str:
    try:
        from streamlift_worker import __version__
        return __version__
    except Exception:
        return "unknown"


def main() -> None:
    config = _bootstrap_config(_parse_args())
    from streamlift_worker.worker import run
    run(config)


if __name__ == "__main__":
    main()