"""
CLI entry point.

Usage (Colab one-liner generated by StreamLift UI):
    streamlift-worker \\
        --worker-id    "uuid" \\
        --auth-token   "token" \\
        --api-url      "https://your-app.com" \\
        --compute-type "medium" \\
        --location     "mega" \\
        --pinggy-token "your-pinggy-token" \\
        --mega-email   "you@example.com" \\
        --mega-password "secret"
"""

import argparse

from streamlift_worker.config import WorkerConfig
from streamlift_worker.worker import run


def _parse_args() -> WorkerConfig:
    p = argparse.ArgumentParser(
        prog="streamlift-worker",
        description="StreamLift distributed download worker",
    )

    p.add_argument("--worker-id",      required=True,  help="Worker UUID from StreamLift dashboard")
    p.add_argument("--auth-token",     required=True,  help="Permanent auth token for this worker")
    p.add_argument("--api-url",        required=True,  help="StreamLift backend base URL")
    p.add_argument("--compute-type",   required=True,  choices=["low", "medium", "high"])
    p.add_argument("--location",       required=True,  choices=["local", "mega"],
                   dest="download_location")
    p.add_argument("--pinggy-token",   required=True,  help="Pinggy tunnel token")
    p.add_argument("--mega-email",     default="",     help="Required when --location=mega")
    p.add_argument("--mega-password",  default="",     help="Required when --location=mega")
    p.add_argument("--port",           default=8000,   type=int, help="Local server port (default 8000)")
    p.add_argument("--version",        action="version", version=f"%(prog)s {_get_version()}")

    args = p.parse_args()

    if args.download_location == "mega" and not (args.mega_email and args.mega_password):
        p.error("--mega-email and --mega-password are required when --location=mega")

    return WorkerConfig(
        worker_id=         args.worker_id,
        auth_token=        args.auth_token,
        api_base_url=      args.api_url.rstrip("/"),
        compute_type=      args.compute_type,
        download_location= args.download_location,
        pinggy_token=      args.pinggy_token,
        mega_email=        args.mega_email,
        mega_password=     args.mega_password,
        server_port=       args.port,
    )


def _get_version() -> str:
    try:
        from streamlift_worker import __version__
        return __version__
    except Exception:
        return "unknown"


def main() -> None:
    config = _parse_args()
    run(config)


if __name__ == "__main__":
    main()
